### ISSUE TITLE
 Vue 3 / Nuxt 3

### ISSUE THREAD

**Issue by waysagency** [qrcode-js/qrcode#2]
Any plans on making this available for Vue 3 / Nuxt 3?

**Comment by ruggi99** [comment]
Hi @waysagency, thanks for reaching.

I don't have any plan into making this available for Vue 3 / Nuxt 3 because this library should, in my opinion, be library / platform agnostic.
This means that, for example, the package @qrcode-js/browser should work in plain html, react, vue, svelte and so on.

By the way I don't know much about Vue and Nuxt.
But I can tell you that I have tried this in NextJS (the equivalent of Nuxt but for React) and it works.

I know that maybe some examples or templates would be useful but the reason why there aren't is because this project is under development.

On the other way I think this project is mature enough to reach stable version and to provide examples / templates

What do you think?

**Comment by waysagency** [comment]
Hi @ruggi99,

I'm sorry for the late answer. I think I've completely missed the notification. I'll try the browser one!

Examples and template would be really nice to have. Besides that, vue doesn't work well with window and document anymore. So I'll let you know if I made a working example
